Repository mitre/vulcan, pull requests merged in 2023-05, with the labels that each got.

#567 VULCAN- 565: Add latest release version tag to Navbar component
  app/javascript/components/navbar/App.vue
  package.json
Labels: javascript, feature request

#569 VULCAN-559: Support for Multiple CCIs
  app/constants/import_constants.rb
  app/models/base_rule.rb
  app/models/component.rb
  app/models/rule.rb
  spec/models/rules_spec.rb
Labels: bug

#580 fix project update logic for detecting name changes correctly
  app/controllers/projects_controller.rb
Labels: bug, V3.0, ruby, vmw, technical

#582 VULCAN-581: Enhance Import from Spreadsheet workflow
  app/models/component.rb
  spec/models/components_spec.rb
Labels: bug

#584 Enabling SMTP feature to send emails via ActionMailer
  app/controllers/application_controller.rb
  app/controllers/memberships_controller.rb
  app/controllers/reviews_controller.rb
  app/javascript/components/rules/RuleEditorHeader.vue
  app/mailers/user_mailer.rb
  app/views/user_mailer/_shared_styles.html.erb
  app/views/user_mailer/approve_review.html.erb
  app/views/user_mailer/request_review.html.erb
  app/views/user_mailer/request_review_changes.html.erb
  app/views/user_mailer/revoke_review.html.erb
  app/views/user_mailer/welcome_component_member.html.erb
  app/views/user_mailer/welcome_project_member.html.erb
  config/initializers/smtp_settings.rb
Labels: V3.0, enhancement, javascript, ruby, vmw, technical

#583 Control View Only and Edit Mode UX refactor
  app/controllers/components_controller.rb
  app/controllers/rule_satisfactions_controller.rb
  app/javascript/components/components/ProjectComponent.vue
  app/javascript/components/rules/FindAndReplace.vue
  app/javascript/components/rules/RuleEditorHeader.vue
  app/javascript/components/rules/RuleNavigator.vue
  app/javascript/components/rules/RuleReviews.vue
  app/javascript/components/rules/RuleSatisfactions.vue
  app/javascript/components/rules/Rules.vue
  app/javascript/components/rules/RulesCodeEditorView.vue
  app/javascript/components/shared/CommentModal.vue
  app/javascript/components/shared/History.vue
  app/javascript/images/child-icon.svg
  app/javascript/images/parent-icon.svg
  app/javascript/mixins/FindAndReplaceMixin.vue
  app/models/base_rule.rb
Labels: enhancement
