Repository mitre/vulcan, pull requests merged in 2023-03, with the labels that each got.

#546 348 alternative testing
  app/controllers/components_controller.rb
  app/javascript/components/components/ProjectComponent.vue
  app/javascript/components/rules/RuleEditorHeader.vue
  app/views/components/show.html.haml
  config/routes.rb
Labels: feature request

#550 customized parser to not interpret character/html entity
  app/models/disa_rule_description.rb
Labels: bug, ruby

#549 389 Integrate Slack With Vulcan
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/components_controller.rb
  app/controllers/memberships_controller.rb
  app/controllers/projects_controller.rb
  app/controllers/security_requirements_guides_controller.rb
  app/controllers/users_controller.rb
  app/helpers/slack_notification_fields_helper.rb
  app/helpers/slack_notifications_helper.rb
  config/initializers/0_settings.rb
  config/initializers/slack.rb
  config/vulcan.default.yml
  docs/config.md
  spec/helpers/slack_notifications_helper_spec.rb
Labels: documentation, V3.0, enhancement, ruby, vmw
