Repository mitre/vulcan, pull requests merged in 2023-09, with the labels that each got.

#605 Enabled viewing of related rules in read-only mode, but hiding the copy button
  app/controllers/rules_controller.rb
  app/javascript/components/components/ProjectComponent.vue
  app/javascript/components/rules/RelatedRulesModal.vue
  app/javascript/components/rules/RulesCodeEditorView.vue
Labels: enhancement

#608 Added fixref attribute to fixtext XML tag for compatibility with stig-viewer-3x
  app/helpers/export_helper.rb
Labels: bug, ruby, vmw, technical

#610 Enable user to select which component to excel export
  app/controllers/projects_controller.rb
  app/helpers/export_helper.rb
  app/javascript/components/project/Project.vue
  spec/helpers/export_helper_spec.rb
Labels: bug, enhancement, vmw

#609 Ensure a rule's inspec code is updated after establishing rule satisfaction or reverting change on a rule
  app/controllers/rule_satisfactions_controller.rb
  app/controllers/rules_controller.rb
  app/models/component.rb
  app/models/rule.rb
  db/seeds.rb
Labels: bug, vmw
